package:
  name: 'annotate'
  version: '1.1'

source:
  git_rev: 1.1
  git_url: https://github.com/arthurvinx/annotate.git

build:
  script: python setup.py install
  string: py27_1

requirements:
  build:
  - setuptools
  - python 2.7.*
  - plyvel
  run:
  - python 2.7.*
  - plyvel
test:
  imports:
      - plyvel

about:
  license: GPL3
  license_file: LICENSE
  home: https://github.com/arthurvinx/annotate
