package:
  name: 'annotate'
  version: '1.0'

source:
  git_url: https://github.com/arthurvinx/annotate.git

build:
  script: python setup.py install

requirements:
  build:
  - setuptools
  - python 3.9.*
  - plyvel 1.3.*
  run:
  - python 3.9.*
  - plyvel 1.3.*

test:
  files:
  - test/diamond.m8
  - test/input.txt
  commands:
  - annotate -v
  - annotate fixplyvel
  - annotate createdb input.txt example 0 1 -d .
  - annotate idmapping diamond.m8 output.txt example -d .

about:
  license: GPL3
  license_file: LICENSE
  home: https://github.com/arthurvinx/annotate
