package:
    name: 'annotate'
    version: '1.1'

source:
    path: ./

build:
    script: python setup.py install

requirements:
    build:
    - python 2.7.*
    - plyvel
    - setuptools
    run:
    - python 2.7.*
    - plyvel

test:
    imports:
        - plyvel

about:
    license: GPL3
    license_file: LICENSE
