package:
  name: 'annotate'
  version: '1.2'

source:
  git_url: https://github.com/arthurvinx/annotate.git

build:
  script: python setup.py install

requirements:
  build:
  - setuptools
  - python 3.9.*
  - plyvel 1.3.*
  run:
  - python 3.9.*
  - plyvel 1.3.*

about:
  license: GPL3
  license_file: LICENSE
  home: https://github.com/arthurvinx/annotate
