package:
  name: 'annotate'
  version: '1.0'

source:
  git_url: https://github.com/arthurvinx/annotate.git

build:
  script: python setup.py install

requirements:
  build:
  - setuptools
  - python 3.9.*
  - plyvel 1.3.*
  run:
  - python 3.9.*
  - plyvel 1.3.*

test:
  files:
  - test/diamond.m8
  - test/input.txt
  - test/output.txt
  requires:
  - pip
  commands:
  - pip3 install -U plyvel --no-cache-dir --no-deps --force-reinstall
  - annotate -v
  - annotate fixplyvel
  - annotate createdb test/input.txt example 0 1 -d .
  - annotate idmapping test/diamond.m8 test.txt example -d .
  - diff test/output.txt test.txt

about:
  license: GPL3
  license_file: LICENSE
  home: https://github.com/arthurvinx/annotate
