package:
    name: 'annotate'
    version: {{ setup_py.get('version') }}

source:
    url: https://github.com/arthurvinx/annotate.git

build:
    script: python setup.py install

requirements:
    build:
    - python 2.7.15 h138c1fe_0
    - setuptools 40.4.3 py27_0
    run:
    - plyvel
    - python 2.7.*

about:
    license: GPL3
    license_file: LICENSE
